# Generated by Django 4.0.4 on 2022-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_coupon_options_alter_itemorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
