# Generated by Django 4.0.4 on 2022-11-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
