# Generated by Django 4.0.4 on 2022-06-15 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='formprofile',
        ),
    ]
