# Generated by Django 4.0.4 on 2022-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_profile_formprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='formprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
