# Generated by Django 4.0.4 on 2022-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_formprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formprofile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='glass_2.jpg', null=True, upload_to='profile/'),
        ),
    ]
