# Generated by Django 4.0.4 on 2022-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_formprofile_options_alter_formprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile/', verbose_name='عکس پروفایل'),
        ),
    ]
