# Generated by Django 4.0.4 on 2022-06-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='category',
        ),
    ]
