# Generated by Django 4.0.4 on 2022-06-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_variantproduct_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantproduct',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productcolor'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productsize'),
        ),
    ]
