# Generated by Django 4.0.4 on 2022-06-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_variantproduct_color_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproduct',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='variantproduct',
            name='size_variant',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='Variantproduct',
        ),
    ]
