# Generated by Django 4.0.4 on 2022-06-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_productcolor_productsize_variantproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantproduct',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productcolor'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='home.product'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productsize'),
        ),
    ]
