# Generated by Django 4.0.4 on 2022-07-04 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_alter_comment_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='com_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
