# Generated by Django 4.0.4 on 2022-07-13 07:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_product_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی ', 'verbose_name_plural': 'دسته بندی ها '},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'رنگ محصول', 'verbose_name_plural': 'رنگ محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'سایز محصول', 'verbose_name_plural': 'سایز محصولات'},
        ),
        migrations.AlterModelOptions(
            name='variantproduct',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_cat',
            field=models.BooleanField(default=False, verbose_name='آیا زیر شاخه است؟'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='home.category', verbose_name='زیر شاخه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_like',
            field=models.ManyToManyField(blank=True, related_name='com_like', to=settings.AUTH_USER_MODEL, verbose_name='پسندیدن نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='آیا ریپلای است؟'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(default=1, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='total_comment_like',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع لایک های نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود است؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='home.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fa_user', to=settings.AUTH_USER_MODEL, verbose_name='علاقه مندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='اطلاعات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'none'), ('Size', 'size'), ('Color', 'color')], max_length=50, null=True, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='نسبت تشابه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین آپدیت'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=20, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productcolor', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='home.product', verbose_name='ویژگی محصول'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.productsize', verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brand', verbose_name='برند'),
        ),
    ]
