# Generated by Django 4.0.4 on 2022-07-16 04:15

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_product_change_variantproduct_change_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproduct',
            name='update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
