# Generated by Django 4.0.4 on 2022-08-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kholase',
            field=models.CharField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.', max_length=500),
        ),
    ]
