# Generated by Django 4.0.4 on 2022-08-11 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blog_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(related_name='views_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
