# Generated by Django 4.0.4 on 2022-08-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_views_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
