# Generated by Django 4.0.4 on 2022-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total',
            field=models.IntegerField(),
        ),
    ]
