# Generated by Django 4.0.4 on 2022-08-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_blog_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
