# Generated by Django 4.0.4 on 2022-08-12 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_remove_blog_views_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
